### ISSUE TITLE
Units error ?

### ISSUE THREAD

**Issue by duboisa1** [energyscope/EnergyScope#10]
When writing the file assets.csv, the units of C_inv and C_maint are referenced as MCHCapitalf/GW whereas I think it should be MCHCapitalf and MCHCapitalf/y to be coherent with their definition earlier in the file.

Same remark for GWP_constr whose unit is specified as ktCO2-eq/GW while it should be just ktCO2-eq. 

I think that the confusion stems from the parameters having the same name but with lower case.

https://github.com/energyscope/EnergyScope/blob/5c092eadddcfe4141b632e172622116ef55147e5/STEP_2_Energy_Model/ESTD_model.mod#L483

**Comment by glimpens** [comment]
Thank you Antoine for your comment.
You are right for these three units.
Moreover, the model is in Euro_{2015}.
Thus I corrected the two units accordingly.

Thank you for supporting us to improve the model :-).
