### ISSUE TITLE
Error while following getting started instruction :  f_max requires numeric data

### ISSUE THREAD

**Issue by AbcSxyZ** [energyscope/EnergyScope#8]
Hi, while working on energyscope during the Sion Climathon (12/03) I had the following issue :

```
$> glpsol -m ESTD_model.mod -d ESTD_data.dat -d ESTD_12TD.dat -o ESTD_output.out
Reading model section from ESTD_model.mod...
ESTD_model.mod:1254: warning: unexpected end of file; missing end statement inserted
1254 lines were read
Reading data section from ESTD_data.dat...
ESTD_data.dat:281: f_max requires numeric data
Context: ...771.9917595 19.55202588 183.79 25 0.961538462 0 1 0 Infinity
MathProg model processing error
```
Using glpk 4.35.

Not sure if it's a version issue with GLPK (didn't try any other version), or if it's an error from my side I do not see what it could be.

We should have work with some members of the project during the climathon, nobody was here so we still try to work on it to share some recommendations, mainly related to how you're open sourcing the software.

Some of you may receive information from the organization team of the climathon, I also did a [LinkedIn post](https://www.linkedin.com/posts/simon-rossi-791692118_openmodels-opensource-passevaccinaldelahonte-activity-6908722915991552000-hBze?utm_source=linkedin_share&utm_medium=member_desktop_web) to speak about it.

**Comment by glimpens** [comment]
Hi,

As indicated at line 278 of ESTD_data.dat, the issue can be solved as it follows:
replace 'Inifinity' by '1e9'
This should be repeated to all the 'Infinity' in this file.

Why using 'Infinity' ?
With AMPL, we use 'Infinity' to foster the resolution.
GLPK doesn't know this command.

Regards,
Gauthier

**Comment by AbcSxyZ** [comment]
The comment in `ESTD_data.data` at line 278 isn't the most appropriate location to give this information. Someone who is following the getting started instruction, using GLPK as recommended, will get this error and won't find this comment. At least it should be documented in the instructions.

Do you have technical benefit for using AMPL over GLPK ? Using non-open source solutions reduce reproducibility, idk if you have a difficult balance between open source vs functionalities of proprietary software.

**Comment by glimpens** [comment]
Hi,

As described in [1], AMPL is +/-  30 times faster than GLPK. 
Thus, when the model must be run several times, AMPL is preferred. 
AMPL License is free of use for master students courses and master thesis.

Both GLPK and AMPL provide the same results*.
Indeed, they solve the same mathematical problem.

Regards,
Gauthier

*AMPL and GLPK do not have the same resolution threshold. Thus, the solution can be almost similar (design and resources used 99% similar). 

[1] Limpens, G., Moret, S., Jeanmart, H., & Maréchal, F. (2019). EnergyScope TD: A novel open-source model for regional energy systems. Applied Energy, 255, 113729.
