### ISSUE TITLE
Documenation: Inconsistencies between Data and Documentation Resources table

### ISSUE THREAD

**Issue by duboisa1** [energyscope/EnergyScope#9]
There are the following inconsistencies between the values of the table in this [section](https://github.com/energyscope/EnergyScope/blob/master/Docs/sections/Input%20Data.rst#imported-resources) of the documentation and the data:

- c_op: the values for biodiesel and bioethanol are inverted
- gwp_op: the values for electricity import are different
- avail: the values for coal are different

**Comment by glimpens** [comment]
Dear Antoine,

Thank you for highlightning these 3 inconsistencies. These have been improved in the documentation as follow:

- c_op: the values for biodiesel and bioethanol were inverted
- gwp_op: the values for electricity import were corrected to the year 2035 (it was another year in previous documentation)
- avail: the values for coal was set to the one used in 2015. As Belgian is phasing out coal, we assume that the amount of coal available is maximum the one of the first year.

Thank you for your contribution :-).
